### ISSUE TITLE
CopyCat!!

### ISSUE THREAD

**Issue by NotYourFrosty** [FirezTheGreat/1SHOT#38]
Hey there! I appreciate your work! but I have a suggestion. This code is being used by **MANY** bots I saw. I saw the same code in many bots, So, I knew it was a code from a public github repo. And so, eventually I found this code. And to make things worse, These copy bots are also available in top.gg! I don't like anyone who copies someone's code and tell that it's "Their bot". So I would appreciate if you would take down this repo or make it private. It's Your hardwork! and not their's!

**Comment by FirezTheGreat** [comment]
Hi there,  Its actually fine by me, i dont mind others copying it, many bots who applied at top.gg are also blacklisted for copying the code from my repo, the mods there are doing there work. I already knew this for a long time but i havent taken any action just because i dont mind it all, what i do is for fun and its totally okay by me if they use my code as theirs.

**Comment by FirezTheGreat** [comment]
changed title cuz its kind of misleading
